// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: compte.proto

package ma.projet.grpc.stubs;

public interface DeleteByIdResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:DeleteByIdResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Indique si la suppression a réussi
   * </pre>
   *
   * <code>bool success = 1;</code>
   * @return The success.
   */
  boolean getSuccess();
}
